# .github/workflows/windows-make.yml
name: Make (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  make-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm install }

      # Optional but recommended: verify app builds/starts in CI
      # - name: Lint / Test
      #   run: npm test

      - name: Make Windows artifacts
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            out/**/*

      # Build AND publish in one go:
      - name: Make & Publish
        run: npx electron-forge publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided automatically
